name: Update DNS Whitelist Rules

on:
  schedule:
    - cron: '0 4 * * *'  # Daily at 04:00 UTC
  workflow_dispatch:

jobs:
  update-whitelist:
    name: Generate and Update Whitelist
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 dnspython

      - name: Run Update Script
        run: python scripts/update_rules.py

      - name: Check for Changes
        id: changes
        run: |
          if git diff --quiet dns-rules/*.txt; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and Push Changes
        if: steps.changes.outputs.has_changes == 'true'
        run: |
          git config user.name "AdGuard Auto-Updater"
          git config user.email "action@github.com"
          git add dns-rules/*.txt
          git commit -m "automated: update DNS whitelist [$(date +'%Y-%m-%d')]"
          git push origin main
